# Generated by Django 3.1 on 2020-08-23 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_description', models.CharField(max_length=7000)),
                ('post_image', models.URLField(default='/media/post_default.jpg')),
                ('post_publish_status', models.BooleanField(default=False)),
                ('post_publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_update_date', models.DateTimeField(auto_now=True, null=True)),
                ('post_created_date', models.DateTimeField(auto_now=True, null=True)),
                ('post_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-post_publish_date',),
            },
        ),
    ]
