# Generated by Django 3.1 on 2020-08-19 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_created_date', models.DateTimeField(auto_created=django.utils.timezone.now)),
                ('post_title', models.CharField(max_length=50)),
                ('post_description', models.CharField(max_length=1000)),
                ('post_image', models.URLField(default='/default.jpg')),
                ('post_publish_status', models.BooleanField(default=False)),
                ('post_publish_date', models.DateTimeField(auto_now_add=True)),
                ('post_update_date', models.DateTimeField(auto_now=True)),
                ('post_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
