# Generated by Django 3.1 on 2020-08-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbs_name', models.CharField(max_length=50)),
                ('fbs_subject', models.CharField(max_length=150)),
                ('fbs_email', models.CharField(max_length=100)),
                ('fbs_message', models.CharField(max_length=1000)),
            ],
        ),
    ]
