# Generated by Django 3.1 on 2020-08-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extapp', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_publish_date',)},
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='profile_pic',
            field=models.URLField(default='/media/profile_pic.png'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.CharField(max_length=7000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.URLField(default='/media/post_default.jpg'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
