# Generated by Django 3.1 on 2020-08-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extapp', '0003_auto_20200821_0144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
